### ISSUE TITLE
player_info

### ISSUE THREAD

**Issue by li-nt** [dsverdlo/minqlx-plugins#4] opened 2016-05-29 06:50 UTC
I just found your plugins, very nice and thank you!

I loaded player_info and it gives the elo on join, but the completed and left game information is not updating.  It seems likely that this relies on another plugin or the database does not have the correct fields that it is calling upon.  Do you have any ideas about this?

**Comment by dsverdlo** [comment] 2016-05-29 12:09
Hello Li-nt,

Thank you for your interest in my plugins.
This is the first time I'm hearing of inconsistencies about the local game information.
Remember that these are stored in the minqlx REDIS database. The ban plugin (part of the default plugins) is responsible for updating the amount of left and completed games.
Only from the moment minqlx was installed, or the database has been moved or reset, the amount of local games per person are tracked.
Admins can change the amount of left games via the !forgive command.

My plugin only shows which values are in the database, so if they are not updating, the cause probably lies elsewhere. I hope this information can help you track down the problem. Feel free to reply here, or drop by IRC (webchat.quakenet.org/?channels=minqlbot).

Best,
Iou

**Comment by li-nt** [comment] 2016-05-29 17:35
Thank you for the reply and confirming all of this.  I was looking at the ban plugin last night due to the handle_game_end function.  It seems that my settings are not keeping track of games because it never posts leavers at the end of a match.

I had the ban plugin loaded, but did not have qlx_leaverBan defined (although the default is 0).  It seems that this is where my problem is located then, and I'll need to troubleshoot.

Perhaps it is because it is in fact 0 and must be enabled to start recording game data.  I am going to try this out and just set the other ban variables very low or high so that it does not ban players.  Thank you again :)

**Comment by li-nt** [comment] 2016-05-29 18:38
For now, I just modified player_info so that it does not report the local games.  It will just output the total played games in the gametype and their elo.

**Comment by dsverdlo** [comment] 2016-05-29 21:08
Alright, indeed seems like a problem with the ban plugin. Well "problem" might not be the correct term for this situation. If leaverban is 0, it will not keep track of leavers (according to 
https://github.com/MinoMino/minqlx-plugins/blob/c69b4b570b59fc1eb30384632841b003f5d96466/ban.py#L89 ). Try enabling this and see if it will track the games then. 

For now I'll close this issue, since it is not one with my plugins, but feel free to come by IRC for further assistance :-)

Cheers

**Closed as completed by dsverdlo** 2016-05-29 21:08 UTC
